version: "3"
services:
  postgres:
    image: postgres
    container_name: "phoneFactory"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phoneFactory
    ports:
      - 5432:5432